development:
  adapter: postgresql
  database: sagitminion
  pool: 5
  timeout: 5000
  username: postgres
  password:
test:
  adapter: postgresql
  database: sagitminion
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sagitminion
  pool: 5
  timeout: 5000
